spring.application.name=pet-location-api
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
logging.level.com.petherson.petlocation=DEBUG

# Geocoding Configuration
geocoding.provider=${GEOCODING_PROVIDER:mock}
geocoding.api.key=${GEOCODING_API_KEY:}
